name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # чтобы импортировался пакет в src/ без установки
      PYTHONPATH: src
      # для воспроизводимости
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
          # если у тебя есть pyproject.toml или setup.cfg — установим пакет (src layout)
          if [ -f pyproject.toml ] || [ -f setup.cfg ]; then pip install -e .; fi

      - name: Sanity import
        run: |
          python - << 'PY'
          import sys, os
          print("sys.path[0]:", sys.path[0])
          print("PYTHONPATH:", os.environ.get("PYTHONPATH"))
          import emailclf
          print("emailclf imported from:", emailclf.__file__)
          PY

      - name: Run tests
        run: pytest -q
